# Minikube overrides
ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  enabled: true
  hosts:
    - host: localhost
      paths:
        - path: /test-app(/|$)(.*)
          pathType: Prefix
